### ISSUE TITLE
Error with Python 3 on OS X

### ISSUE THREAD

**Issue by uranusjr** [Russell91/runcython#3]
~~~
$ python -V
Python 3.5.0

$ cat main.pyx
def main():
    print('Hello!')

$ runcython main.pyx
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: dynamic module does not define module export function (PyInit_main)
~~~

**Comment by Russell91** [comment]
Perhaps your python.pc file is configured for python2 rather than python3? These guys seem to be having a similar [issue](http://stackoverflow.com/questions/29657319/dynamic-module-does-not-define-init-function-pyinit-fuzzy).

"Cython generates code that should compile to work in Python 2 or 3, depending on which headers are included"

python3 may take first priority on your path, but cython needs to know what version of the python headers to compile against before the python executable is ever invoked. Perhaps the fix is as simple as adding python3.pc to your PKG_CONFIG_PATH rather than python.pc?

Good issue to bring up though!

**Comment by uranusjr** [comment]
:+1:
